# Permalinks
permalink:           pretty

# Setup
title:               Progress
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
url:                http://yooniversal.github.io
baseurl:          
analytics_id:

# Owner/author information
owner:
  name:          Yoon DongBin
  avatar:         avatar.png
  bio:            "Student."
  email:          iteratively@naver.com
  twitter:        alexanderussell
  github:         yooniversal
  instagram:      everywherelse
  dribbble:       alexanderussell
  location:       "Icheon, KR"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate

remote_theme : alexanderussell/progress-for-jekyll